"""make employee name unique

Revision ID: 1976d4ca62e1
Revises: 5445a9f3cfd8
Create Date: 2026-02-26 18:04:37.688972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1976d4ca62e1'
down_revision: Union[str, None] = '5445a9f3cfd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_employees_nama', table_name='employees')
    op.create_index(op.f('ix_employees_nama'), 'employees', ['nama'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_nama'), table_name='employees')
    op.create_index('ix_employees_nama', 'employees', ['nama'], unique=False)
    # ### end Alembic commands ###
