"""add cascade delete to devices and users

Revision ID: 37e2388db79d
Revises: 8c79171d62cc
Create Date: 2026-03-01 21:45:25.764871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '37e2388db79d'
down_revision: Union[str, None] = '8c79171d62cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device_condition_change_requests', 'loan_item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('device_condition_change_requests', 'requested_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('device_condition_change_requests_reviewed_by_admin_id_fkey', 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint('device_condition_change_requests_loan_item_id_fkey', 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint('device_condition_change_requests_child_device_id_fkey', 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint('device_condition_change_requests_requested_by_user_id_fkey', 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint('device_condition_change_requests_device_id_fkey', 'device_condition_change_requests', type_='foreignkey')
    op.create_foreign_key(None, 'device_condition_change_requests', 'users', ['reviewed_by_admin_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'device_condition_change_requests', 'device_loan_items', ['loan_item_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'device_condition_change_requests', 'users', ['requested_by_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'device_condition_change_requests', 'devices', ['device_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'device_condition_change_requests', 'device_children', ['child_device_id'], ['id'], ondelete='CASCADE')
    op.alter_column('device_group_items', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('device_group_items_group_id_fkey', 'device_group_items', type_='foreignkey')
    op.create_foreign_key(None, 'device_group_items', 'device_groups', ['group_id'], ['id'], ondelete='CASCADE')
    op.alter_column('device_groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('device_groups_user_id_fkey', 'device_groups', type_='foreignkey')
    op.create_foreign_key(None, 'device_groups', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('device_loan_items', 'loan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('device_loan_items_device_id_fkey', 'device_loan_items', type_='foreignkey')
    op.drop_constraint('device_loan_items_loan_id_fkey', 'device_loan_items', type_='foreignkey')
    op.drop_constraint('device_loan_items_child_device_id_fkey', 'device_loan_items', type_='foreignkey')
    op.create_foreign_key(None, 'device_loan_items', 'device_loans', ['loan_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'device_loan_items', 'device_children', ['child_device_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'device_loan_items', 'devices', ['device_id'], ['id'], ondelete='SET NULL')
    op.alter_column('device_loans', 'borrower_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('device_loans_borrower_user_id_fkey', 'device_loans', type_='foreignkey')
    op.drop_constraint('device_loans_returned_by_user_id_fkey', 'device_loans', type_='foreignkey')
    op.drop_constraint('device_loans_pihak_2_id_fkey', 'device_loans', type_='foreignkey')
    op.drop_constraint('device_loans_pihak_1_id_fkey', 'device_loans', type_='foreignkey')
    op.create_foreign_key(None, 'device_loans', 'users', ['returned_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'device_loans', 'employees', ['pihak_2_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'device_loans', 'users', ['borrower_user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'device_loans', 'employees', ['pihak_1_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('employees_user_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('loan_history', 'loan_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('loan_history_loan_id_fkey', 'loan_history', type_='foreignkey')
    op.drop_constraint('loan_history_changed_by_user_id_fkey', 'loan_history', type_='foreignkey')
    op.create_foreign_key(None, 'loan_history', 'users', ['changed_by_user_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'loan_history', 'device_loans', ['loan_id'], ['id'], ondelete='CASCADE')
    op.alter_column('mfa_backup_codes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('mfa_backup_codes_user_id_fkey', 'mfa_backup_codes', type_='foreignkey')
    op.create_foreign_key(None, 'mfa_backup_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('password_reset_tokens_user_id_fkey', 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.drop_constraint('user_roles_role_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_roles', 'roles', ['role_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_role_id_fkey', 'user_roles', 'roles', ['role_id'], ['id'])
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'users', ['user_id'], ['id'])
    op.alter_column('user_roles', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key('password_reset_tokens_user_id_fkey', 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.alter_column('password_reset_tokens', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'mfa_backup_codes', type_='foreignkey')
    op.create_foreign_key('mfa_backup_codes_user_id_fkey', 'mfa_backup_codes', 'users', ['user_id'], ['id'])
    op.alter_column('mfa_backup_codes', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'loan_history', type_='foreignkey')
    op.drop_constraint(None, 'loan_history', type_='foreignkey')
    op.create_foreign_key('loan_history_changed_by_user_id_fkey', 'loan_history', 'users', ['changed_by_user_id'], ['id'])
    op.create_foreign_key('loan_history_loan_id_fkey', 'loan_history', 'device_loans', ['loan_id'], ['id'])
    op.alter_column('loan_history', 'loan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_user_id_fkey', 'employees', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'device_loans', type_='foreignkey')
    op.drop_constraint(None, 'device_loans', type_='foreignkey')
    op.drop_constraint(None, 'device_loans', type_='foreignkey')
    op.drop_constraint(None, 'device_loans', type_='foreignkey')
    op.create_foreign_key('device_loans_pihak_1_id_fkey', 'device_loans', 'employees', ['pihak_1_id'], ['id'])
    op.create_foreign_key('device_loans_pihak_2_id_fkey', 'device_loans', 'employees', ['pihak_2_id'], ['id'])
    op.create_foreign_key('device_loans_returned_by_user_id_fkey', 'device_loans', 'users', ['returned_by_user_id'], ['id'])
    op.create_foreign_key('device_loans_borrower_user_id_fkey', 'device_loans', 'users', ['borrower_user_id'], ['id'])
    op.alter_column('device_loans', 'borrower_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'device_loan_items', type_='foreignkey')
    op.drop_constraint(None, 'device_loan_items', type_='foreignkey')
    op.drop_constraint(None, 'device_loan_items', type_='foreignkey')
    op.create_foreign_key('device_loan_items_child_device_id_fkey', 'device_loan_items', 'device_children', ['child_device_id'], ['id'])
    op.create_foreign_key('device_loan_items_loan_id_fkey', 'device_loan_items', 'device_loans', ['loan_id'], ['id'])
    op.create_foreign_key('device_loan_items_device_id_fkey', 'device_loan_items', 'devices', ['device_id'], ['id'])
    op.alter_column('device_loan_items', 'loan_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'device_groups', type_='foreignkey')
    op.create_foreign_key('device_groups_user_id_fkey', 'device_groups', 'users', ['user_id'], ['id'])
    op.alter_column('device_groups', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'device_group_items', type_='foreignkey')
    op.create_foreign_key('device_group_items_group_id_fkey', 'device_group_items', 'device_groups', ['group_id'], ['id'])
    op.alter_column('device_group_items', 'group_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'device_condition_change_requests', type_='foreignkey')
    op.create_foreign_key('device_condition_change_requests_device_id_fkey', 'device_condition_change_requests', 'devices', ['device_id'], ['id'])
    op.create_foreign_key('device_condition_change_requests_requested_by_user_id_fkey', 'device_condition_change_requests', 'users', ['requested_by_user_id'], ['id'])
    op.create_foreign_key('device_condition_change_requests_child_device_id_fkey', 'device_condition_change_requests', 'device_children', ['child_device_id'], ['id'])
    op.create_foreign_key('device_condition_change_requests_loan_item_id_fkey', 'device_condition_change_requests', 'device_loan_items', ['loan_item_id'], ['id'])
    op.create_foreign_key('device_condition_change_requests_reviewed_by_admin_id_fkey', 'device_condition_change_requests', 'users', ['reviewed_by_admin_id'], ['id'])
    op.alter_column('device_condition_change_requests', 'requested_by_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('device_condition_change_requests', 'loan_item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
