"""replace username with nama add nip jabatan user_id

Revision ID: 3a80bbb3a1bb
Revises: 
Create Date: 2026-02-03 22:50:46.381140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3a80bbb3a1bb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Skip dropping loan_history_backup if it doesn't exist or is needed
    # op.drop_table('loan_history_backup')
    
    # Add foreign key constraints for condition change requests (if not exist)
    try:
        op.create_foreign_key(None, 'device_condition_change_requests', 'device_loan_items', ['loan_item_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key(None, 'device_condition_change_requests', 'users', ['requested_by_user_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key(None, 'device_condition_change_requests', 'users', ['reviewed_by_admin_id'], ['id'])
    except:
        pass
    
    # Employee model changes
    op.add_column('employees', sa.Column('user_id', sa.Integer(), nullable=True))
    op.alter_column('employees', 'nip',
               existing_type=sa.VARCHAR(),
               nullable=True)
    try:
        op.drop_index('ix_employees_nip', table_name='employees')
    except:
        pass
    op.create_index(op.f('ix_employees_nip'), 'employees', ['nip'], unique=False)
    op.create_unique_constraint('uq_employees_user_id', 'employees', ['user_id'])
    op.create_foreign_key('fk_employees_user_id', 'employees', 'users', ['user_id'], ['id'])
    
    # Other foreign keys (if not exist)
    try:
        op.create_foreign_key(None, 'mfa_backup_codes', 'users', ['user_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'])
    except:
        pass
    try:
        op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'])
    except:
        pass
    
    # User model changes - Step 1: Add nama as nullable first
    op.add_column('users', sa.Column('nama', sa.String(255), nullable=True))
    op.add_column('users', sa.Column('nip', sa.String(50), nullable=True))
    op.add_column('users', sa.Column('jabatan', sa.String(255), nullable=True))
    
    # Step 2: Copy data from username to nama
    op.execute("UPDATE users SET nama = username WHERE nama IS NULL")
    
    # Step 3: Make nama non-nullable
    op.alter_column('users', 'nama', nullable=False)
    
    # Step 4: Drop username column and its index
    try:
        op.drop_index('ix_users_username', table_name='users')
    except:
        pass
    op.drop_column('users', 'username')
    
    # Step 5: Create index on nama
    op.create_index(op.f('ix_users_nama'), 'users', ['nama'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_nama'), table_name='users')
    op.create_index('ix_users_username', 'users', ['username'], unique=True)
    op.drop_column('users', 'jabatan')
    op.drop_column('users', 'nip')
    op.drop_column('users', 'nama')
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.drop_constraint(None, 'mfa_backup_codes', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_constraint(None, 'employees', type_='unique')
    op.drop_index(op.f('ix_employees_nip'), table_name='employees')
    op.create_index('ix_employees_nip', 'employees', ['nip'], unique=True)
    op.alter_column('employees', 'nip',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('employees', 'user_id')
    op.drop_constraint(None, 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'device_condition_change_requests', type_='foreignkey')
    op.drop_constraint(None, 'device_condition_change_requests', type_='foreignkey')
    op.create_table('loan_history_backup',
    sa.Column('created_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('deleted_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('loan_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('old_status', postgresql.ENUM('ACTIVE', 'RETURNED', 'OVERDUE', 'CANCELLED', name='loanstatus'), autoincrement=False, nullable=True),
    sa.Column('new_status', postgresql.ENUM('ACTIVE', 'RETURNED', 'OVERDUE', 'CANCELLED', name='loanstatus'), autoincrement=False, nullable=True),
    sa.Column('change_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('changed_by_user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('change_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
