"""add all_code to devices

Revision ID: 5445a9f3cfd8
Revises: d72665b90f93
Create Date: 2026-02-26 17:47:50.242706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5445a9f3cfd8'
down_revision: Union[str, None] = 'd72665b90f93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('all_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.execute("UPDATE devices SET all_code = CONCAT(device_code, COALESCE(nup_device, ''))")
    op.alter_column('devices', 'all_code', nullable=False)
    op.drop_constraint('uq_device_code_nup', 'devices', type_='unique')
    op.create_index(op.f('ix_devices_all_code'), 'devices', ['all_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_devices_all_code'), table_name='devices')
    op.create_unique_constraint('uq_device_code_nup', 'devices', ['device_code', 'nup_device'], postgresql_nulls_not_distinct=False)
    op.drop_column('devices', 'all_code')
    # ### end Alembic commands ###
