"""Make borrower_user_id SET NULL

Revision ID: 626a4c6af4a8
Revises: 37e2388db79d
Create Date: 2026-04-24 06:45:37.954149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '626a4c6af4a8'
down_revision: Union[str, None] = '37e2388db79d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('device_condition_change_requests_requested_by_user_id_fkey', 'device_condition_change_requests', type_='foreignkey')
    op.create_foreign_key(None, 'device_condition_change_requests', 'users', ['requested_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('device_loans_borrower_user_id_fkey', 'device_loans', type_='foreignkey')
    op.create_foreign_key(None, 'device_loans', 'users', ['borrower_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'device_loans', type_='foreignkey')
    op.create_foreign_key('device_loans_borrower_user_id_fkey', 'device_loans', 'users', ['borrower_user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'device_condition_change_requests', type_='foreignkey')
    op.create_foreign_key('device_condition_change_requests_requested_by_user_id_fkey', 'device_condition_change_requests', 'users', ['requested_by_user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
