"""add_is_pihak_1_to_employees

Revision ID: 8c79171d62cc
Revises: 1976d4ca62e1
Create Date: 2026-02-26 22:31:34.269788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8c79171d62cc'
down_revision: Union[str, None] = '1976d4ca62e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('is_pihak_1', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'is_pihak_1')
    # ### end Alembic commands ###
