"""Initial Schema

Revision ID: c1aa42d7e220
Revises: 
Create Date: 2026-02-20 15:46:11.529820

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c1aa42d7e220'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nup_device', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bmn_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sample_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_year', sa.Integer(), nullable=True),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_station', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_status', sa.Enum('TERSEDIA', 'DIPINJAM', 'MAINTENANCE', 'NONAKTIF', name='devicestatus'), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_room', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photos_url', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devices_device_code'), 'devices', ['device_code'], unique=False)
    op.create_index(op.f('ix_devices_device_name'), 'devices', ['device_name'], unique=False)
    op.create_table('locations',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('users',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('nip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jabatan', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('password_history', sa.JSON(), nullable=True),
    sa.Column('force_password_change', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('lockout_duration_minutes', sa.Integer(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('mfa_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_nama'), 'users', ['nama'], unique=False)
    op.create_table('device_children',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('device_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('device_code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nup_device', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('bmn_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sample_brand', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_year', sa.Integer(), nullable=True),
    sa.Column('device_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_station', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_status', sa.Enum('TERSEDIA', 'DIPINJAM', 'MAINTENANCE', 'NONAKTIF', name='devicestatus'), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_room', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('photos_url', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['devices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_children_device_code'), 'device_children', ['device_code'], unique=False)
    op.create_index(op.f('ix_device_children_device_name'), 'device_children', ['device_name'], unique=False)
    op.create_index(op.f('ix_device_children_parent_id'), 'device_children', ['parent_id'], unique=False)
    op.create_table('device_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_groups_name'), 'device_groups', ['name'], unique=False)
    op.create_table('employees',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nama', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('nip', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('jabatan', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_employees_nama'), 'employees', ['nama'], unique=False)
    op.create_index(op.f('ix_employees_nip'), 'employees', ['nip'], unique=False)
    op.create_table('mfa_backup_codes',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mfa_backup_codes_code'), 'mfa_backup_codes', ['code'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_password_reset_tokens_token'), 'password_reset_tokens', ['token'], unique=True)
    op.create_table('user_roles',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_group_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('child_device_id', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['child_device_id'], ['device_children.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['group_id'], ['device_groups.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_loans',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pihak_1_id', sa.Integer(), nullable=True),
    sa.Column('pihak_2_id', sa.Integer(), nullable=True),
    sa.Column('assignment_letter_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('assignment_letter_date', sa.Date(), nullable=False),
    sa.Column('borrower_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('borrower_user_id', sa.Integer(), nullable=False),
    sa.Column('activity_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('usage_duration_days', sa.Integer(), nullable=False),
    sa.Column('loan_start_date', sa.Date(), nullable=False),
    sa.Column('loan_end_date', sa.Date(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actual_return_date', sa.Date(), nullable=True),
    sa.Column('return_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('returned_by_user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['borrower_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pihak_1_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['pihak_2_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['returned_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_device_loans_assignment_letter_number'), 'device_loans', ['assignment_letter_number'], unique=False)
    op.create_index(op.f('ix_device_loans_loan_number'), 'device_loans', ['loan_number'], unique=True)
    op.create_table('device_loan_items',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('child_device_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('condition_before', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('condition_after', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condition_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['child_device_id'], ['device_children.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['device_loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('loan_history',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_id', sa.Integer(), nullable=False),
    sa.Column('old_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('change_reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('changed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('change_date', sa.DateTime(), nullable=False),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['loan_id'], ['device_loans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_condition_change_requests',
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('loan_item_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('child_device_id', sa.Integer(), nullable=True),
    sa.Column('requested_by_user_id', sa.Integer(), nullable=False),
    sa.Column('old_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('new_condition', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reason', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evidence_photo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_by_admin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['child_device_id'], ['device_children.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['loan_item_id'], ['device_loan_items.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by_admin_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_condition_change_requests')
    op.drop_table('loan_history')
    op.drop_table('device_loan_items')
    op.drop_index(op.f('ix_device_loans_loan_number'), table_name='device_loans')
    op.drop_index(op.f('ix_device_loans_assignment_letter_number'), table_name='device_loans')
    op.drop_table('device_loans')
    op.drop_table('device_group_items')
    op.drop_table('user_roles')
    op.drop_index(op.f('ix_password_reset_tokens_token'), table_name='password_reset_tokens')
    op.drop_table('password_reset_tokens')
    op.drop_index(op.f('ix_mfa_backup_codes_code'), table_name='mfa_backup_codes')
    op.drop_table('mfa_backup_codes')
    op.drop_index(op.f('ix_employees_nip'), table_name='employees')
    op.drop_index(op.f('ix_employees_nama'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_device_groups_name'), table_name='device_groups')
    op.drop_table('device_groups')
    op.drop_index(op.f('ix_device_children_parent_id'), table_name='device_children')
    op.drop_index(op.f('ix_device_children_device_name'), table_name='device_children')
    op.drop_index(op.f('ix_device_children_device_code'), table_name='device_children')
    op.drop_table('device_children')
    op.drop_index(op.f('ix_users_nama'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_locations_name'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_devices_device_name'), table_name='devices')
    op.drop_index(op.f('ix_devices_device_code'), table_name='devices')
    op.drop_table('devices')
    # ### end Alembic commands ###
