"""add_unique_constraints

Revision ID: d72665b90f93
Revises: c4d5e6f7g8h9
Create Date: 2026-02-26 17:22:14.948126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd72665b90f93'
down_revision: Union[str, None] = 'c4d5e6f7g8h9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_child_device_code_nup', 'device_children', ['device_code', 'nup_device'])
    op.create_unique_constraint('uq_device_code_nup', 'devices', ['device_code', 'nup_device'])
    op.drop_index('ix_employees_nip', table_name='employees')
    op.create_index(op.f('ix_employees_nip'), 'employees', ['nip'], unique=True)
    op.drop_constraint('employees_user_id_fkey', 'employees', type_='foreignkey')
    op.create_foreign_key(None, 'employees', 'users', ['user_id'], ['id'])
    op.create_unique_constraint('uq_location_name_type', 'locations', ['name', 'type'])
    op.drop_constraint('mfa_backup_codes_user_id_fkey', 'mfa_backup_codes', type_='foreignkey')
    op.create_foreign_key(None, 'mfa_backup_codes', 'users', ['user_id'], ['id'])
    op.drop_constraint('password_reset_tokens_user_id_fkey', 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'password_reset_tokens', 'users', ['user_id'], ['id'])
    op.drop_constraint('user_roles_user_id_fkey', 'user_roles', type_='foreignkey')
    op.create_foreign_key(None, 'user_roles', 'users', ['user_id'], ['id'])
    op.drop_constraint('uq_users_uuid', 'users', type_='unique')
    op.drop_index('ix_users_uuid', table_name='users')
    op.create_index(op.f('ix_users_uuid'), 'users', ['uuid'], unique=True)
    op.create_unique_constraint(None, 'users', ['nip'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_index(op.f('ix_users_uuid'), table_name='users')
    op.create_index('ix_users_uuid', 'users', ['uuid'], unique=False)
    op.create_unique_constraint('uq_users_uuid', 'users', ['uuid'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'user_roles', type_='foreignkey')
    op.create_foreign_key('user_roles_user_id_fkey', 'user_roles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'password_reset_tokens', type_='foreignkey')
    op.create_foreign_key('password_reset_tokens_user_id_fkey', 'password_reset_tokens', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'mfa_backup_codes', type_='foreignkey')
    op.create_foreign_key('mfa_backup_codes_user_id_fkey', 'mfa_backup_codes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_location_name_type', 'locations', type_='unique')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.create_foreign_key('employees_user_id_fkey', 'employees', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_employees_nip'), table_name='employees')
    op.create_index('ix_employees_nip', 'employees', ['nip'], unique=False)
    op.drop_constraint('uq_device_code_nup', 'devices', type_='unique')
    op.drop_constraint('uq_child_device_code_nup', 'device_children', type_='unique')
    # ### end Alembic commands ###
